Github action to check metadata lines in scripts.
community-scripts/ProxmoxVE pull request #1110
Opened 2024-12-30 12:18 UTC by quantumryuu

> **🛠️ Note:**  
> We are meticulous about merging code into the main branch, so please understand that pull requests not meeting the project's standards may be rejected. It's never personal!  
> 🎮 **Note for game-related scripts:** These have a lower likelihood of being merged.

---

## ✍️ Description
Github action to check the following:

* \# Copyright (c) 2021-2024 community-scripts ORG
Check if it exists in line 3
* \# Author: [Name] (also checks if there is text after the space"
Check if it exists in line 4 & that it has text after the space
* \# License: MIT | https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE
Check if it exists in line 5
* \# Source: [Source] (also checks if there is text after the space"
Check if it exists in line 6 & that it has text after the space
 

 

- - -
**_Please remove unneeded lines!_**
- Related PR: #920  (if applicable)  
- Related Discussion: [https://github.com/community-scripts/ProxmoxVE/pull/920#issuecomment-2564734581](https://github.com/community-scripts/ProxmoxVE/pull/920#issuecomment-2564734581) and https://github.com/community-scripts/ProxmoxVE/pull/920#issuecomment-2564842549

---

## 🛠️ Type of Change
Please check the relevant options:  
- [ ] Bug fix (non-breaking change that resolves an issue)  
- [x] New feature (non-breaking change that adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to change unexpectedly)  
- [ ] New script (a fully functional and thoroughly tested script or set of scripts)  

---

## ✅ Prerequisites
The following steps must be completed for the pull request to be considered:  
- [x] Self-review performed (I have reviewed my code to ensure it follows established patterns and conventions.)  
- [x] Testing performed (I have thoroughly tested my changes and verified expected functionality.)  
- [ ] Documentation updated (I have updated any relevant documentation)

---

## 📋 Additional Information (optional)
Provide any extra context or screenshots about the feature or fix here.

2024-12-30 16:43 UTC, MickLesk submitted a review, later dismissed

2024-12-30 17:06 UTC, michelroegl-brunner requested changes

2024-12-30 19:46 UTC, michelroegl-brunner submitted a review, later dismissed

2024-12-30 20:29 UTC, se-bastiaan commented on .github/workflows/check-metadata.yml
> +'on':
```suggestion
on:
```

2024-12-30 20:29 UTC, se-bastiaan commented on .github/workflows/check-metadata.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v4
```

2024-12-30 20:29 UTC, se-bastiaan commented on .github/workflows/check-metadata.yml
> +        shell: bash
I would suggest splitting this up into 5 steps each with their own output (using `echo "errors=$ERROR_COUNT" >> $GITHUB_OUTPUT`: 
 - Find files to check
 - Check Copyright line
 - Check author line(s)
 - Check license line
 - Check source line

And then a 6th step that creates or updates a comment with the state of this workflow depending on the output of the previous steps along the lines of:
```
     - uses: actions/github-script@v7
       if: ${{ steps.authors.outputs.errors != '0' && ... etc }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Your PR currently contain files with headers that do not match our requirements: ${filenames}'
            })
```

But I can understand that that is not necessary for a first version.

2024-12-30 20:29 UTC, se-bastiaan commented on .github/workflows/check-metadata.yml
> +            fi
Does this work with one or multiple co-authors?

2025-01-01 12:27 UTC, MickLesk approved these changes

2025-01-01 15:41 UTC, michelroegl-brunner approved these changes

2025-01-01 16:03 UTC, se-bastiaan commented on .github/workflows/check-metadata.yml
> +            fi
I don't completely understand how this is resolved.

2025-01-03 18:31 UTC, merged