Add CUPS printing system
community-scripts/ProxmoxVE pull request #637
Opened 2024-12-02 10:28 UTC by zdraganov

## Description

Adding CUPS print server as LXE container installation

Fixes # (issue)

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [X] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [ ] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [X] Testing performed (I have tested my changes, ensuring everything works as expected)
- [X] Documentation updated (I have updated any relevant documentation)

## Related Pull Requests / Discussions

2024-12-02 12:18 UTC, michelroegl-brunner requested changes

2024-12-02 12:18 UTC, michelroegl-brunner commented on install/cups-install.sh
> +msg_ok "Installed Dependencies"
```
$STD apt-get install -y \
  curl \
  sudo \
  mc 
```
This is Standard.

2024-12-02 12:18 UTC, michelroegl-brunner commented on json/cups.json
> +  "slug": "CUPS",
`cups`

Lowercase

2024-12-02 12:18 UTC, michelroegl-brunner commented on json/cups.json
> +      "username": "root",
Leave it as null if not needed.

2024-12-02 12:18 UTC, michelroegl-brunner commented on install/cups-install.sh
> +msg_info "Install CUPS"
Rename to Creating Service

2024-12-02 12:18 UTC, michelroegl-brunner commented on install/cups-install.sh
> +msg_ok "Added lpadmin to root group"
Put in same msg_info "Creating Service" as above

2024-12-02 12:18 UTC, michelroegl-brunner commented on install/cups-install.sh
> +msg_ok "Started Service"
Put in same msg_info "Creating Service" as above

2024-12-02 12:18 UTC, michelroegl-brunner commented on install/cups-install.sh
> +msg_ok "Allowed remote administration"
Put in same msg_info "Creating Service" as above

msg_ok "Configured Service"

2024-12-02 13:34 UTC, michelroegl-brunner reviewed
Looks good for me, but @MickLesk or @havardthom still need to have a look to aprove the PR for merging.

2024-12-03 00:23 UTC, newzealandpaul commented
@zdraganov, your JSON file is incorrect, the version of CUPS installed is this version: https://openprinting.github.io/cups/

Overall, does this need to be a script? It does not do a whole lot. I think using the Debian LXC script and simply doing an `apt install` is enough.

2024-12-03 07:14 UTC, zdraganov commented
> Overall, does this need to be a script? It does not do a whole lot. I think using the Debian LXC script and simply doing an `apt install` is enough.

Most of the scripts are installing something, enable service - then configure it initially via the exposed web/terminal UI.
My feeling that cups is very common software that was just missing from the ProxmoxVE scripts and can help the people.

2024-12-03 07:23 UTC, MickLesk commented on ct/cups.sh
> +# Copyright (c) 2021-2024 tteck
community-scripts ORG

2024-12-03 07:23 UTC, MickLesk commented on ct/cups.sh
> +# Author: tteck (tteckster)
YourUserName

2024-12-03 07:23 UTC, MickLesk commented on ct/cups.sh
> +msg_info "Updating..."
msg_info "Updating ${APP}"

2024-12-03 07:23 UTC, MickLesk commented on ct/cups.sh
> +msg_ok "Update Successfully"
msg_ok "Updated ${APP}"

2024-12-03 18:16 UTC, MickLesk commented on install/cups-install.sh
> +# Copyright (c) 2021-2024 tteck
community-scripts ORG

2024-12-03 18:16 UTC, MickLesk commented on install/cups-install.sh
> +# Author: tteck (tteckster)
Your UserName

2024-12-03 18:16 UTC, MickLesk commented on install/cups-install.sh
> +msg_ok "Configured Service"
Split this into 2 Sections

MSG Setup Cups

MSG Creating Service

2024-12-03 20:15 UTC, newzealandpaul commented
> Most of the scripts are installing something, enable service - then configure it initially via the exposed web/terminal UI.
> My feeling that cups is very common software that was just missing from the ProxmoxVE scripts and can help the people.

But without hardware passthrough its not useful out of the box. 

Usually, but not always, installing involves more than a single command. 

@zdraganov I appreciate the effort you put into this. There were a significant number of errors, including misidentifying the package being installed. I don't believe we should merge this.

2024-12-03 20:18 UTC, zdraganov commented
Makes sense. Closing this one.

2024-12-03 20:18 UTC, closed without merging

2025-03-30 01:21 UTC, VNRARA commented
Damn.. I was really looking for something like this.. I can't for the life of me get a LXC with CUPS going.. 
I just can't reach 631/admin whenever it's setup no matter the other settings I tweak.